Bangazon/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Bangazon.Models
{
  public class Order
  {
    [Key]
    public int OrderId {get;set;}

    [Required]
    [DataType(DataType.Date)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime DateCreated {get;set;}

    [DataType(DataType.Date)]
    public DateTime? DateCompleted {get;set;}

    [Required]
    public string UserId {get; set;}

    [Required]
    public ApplicationUser User { get; set; }

    public int? PaymentTypeId {get;set;}
    public PaymentType PaymentType {get;set;}

    public virtual ICollection<OrderProduct> OrderProducts { get; set; }
  }
}

Bangazon/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bangazon.Data;
using Bangazon.Models;
using Microsoft.AspNetCore.Identity;
using Bangazon.Models.OrderViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Bangazon.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        public OrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Order.Include(o => o.PaymentType).Include(o => o.User);
            return View(await applicationDbContext.ToListAsync());
        }


        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o.PaymentType)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["PaymentTypeId"] = new SelectList(_context.PaymentType, "PaymentTypeId", "AccountNumber");
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,DateCreated,DateCompleted,UserId,PaymentTypeId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaymentTypeId"] = new SelectList(_context.PaymentType, "PaymentTypeId", "AccountNumber", order.PaymentTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", order.UserId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["PaymentTypeId"] = new SelectList(_context.PaymentType, "PaymentTypeId", "AccountNumber", order.PaymentTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", order.UserId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,DateCreated,DateCompleted,UserId,PaymentTypeId")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PaymentTypeId"] = new SelectList(_context.PaymentType, "PaymentTypeId", "AccountNumber", order.PaymentTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", order.UserId);
            return View(order);
        }

        [Authorize]
        public async Task<IActionResult> DeleteOrderProduct(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderProduct = await _context.OrderProduct
                .Include(o => o.Order)
                .Include(o => o.Product)
                .FirstOrDefaultAsync(m => m.OrderProductId == id);
            if (orderProduct == null)
            {
                return NotFound();
            }

            return View(orderProduct);
        }

        // POST: OrderProducts/Delete/5
        [HttpPost, ActionName("DeleteOrderProduct")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteODConfirmed(int id)
        {
            var orderProduct = await _context.OrderProduct.FindAsync(id);
            _context.OrderProduct.Remove(orderProduct);
            await _context.SaveChangesAsync();
            return RedirectToAction("ViewCart", "Orders", new { id = orderProduct.OrderId });
        }





        // GET: Orders/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = await _context.Order
               .Include(o => o.PaymentType)
               .Include(o => o.User)
               .Include(o => o.OrderProducts)
               .ThenInclude(op => op.Product)
               .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderProducts = await _context.OrderProduct.Where(op => op.OrderId == id).ToListAsync();
            foreach (var item in orderProducts)
            {
                _context.OrderProduct.Remove(item);
            }
            await _context.SaveChangesAsync();
            var order = await _context.Order.FindAsync(id);
            _context.Order.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ViewCart));
        }
        [Authorize]
        public async Task<IActionResult> ViewCart(int id)
        {

            var viewModel = new OrderDetailViewModel();

            var currentUser = await GetCurrentUserAsync();
            Order order = await _context.Order
                .Include(o => o.PaymentType)
                .Include(o => o.User)
                .ThenInclude(U => U.PaymentTypes)
                .Include(o => o.OrderProducts)
                .ThenInclude(op => op.Product)
                .FirstOrDefaultAsync(m => m.UserId == currentUser.Id.ToString() && m.PaymentTypeId == null);

            viewModel.Order = order;

            if (order == null || order.PaymentType != null)
            {
                return View(viewModel);
            }
            viewModel.LineItems = order.OrderProducts
                .GroupBy(op => op.Product)
                .Select(g => new OrderLineItem
                {
                    Product = g.Key,
                    Units = g.Select(x => x.Product).Count(),
                    Cost = g.Key.Price * g.Select(x => x.ProductId).Count()
                }).ToList();
            return View(viewModel);
        }

        private bool OrderExists(int id)
        {
            return _context.Order.Any(e => e.OrderId == id);
        }


        public async Task<IActionResult> AddToOrder(int Id)
        {
            ModelState.Remove("UserId");
            ModelState.Remove("User");
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User);
                List<Order> activeOrders = _context.Order.Where(o => o.UserId == user.Id && o.PaymentType == null).ToList();
                
                
                if (!activeOrders.Any())
                {
                    _context.Add(new Order { UserId = user.Id });
                    await _context.SaveChangesAsync();
                    List<Order> newActiveOrder = _context.Order.Where(o => o.UserId == user.Id && o.PaymentType == null).ToList();
                    Order currentOrder = newActiveOrder[0];
                    _context.OrderProduct.Add(new OrderProduct { ProductId = Id, OrderId = currentOrder.OrderId});
                }
                else
                {
                    Order currentOrder = activeOrders[0];
                    _context.OrderProduct.Add(new OrderProduct { ProductId = Id, OrderId = currentOrder.OrderId});
                }


                  
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Details", "Products");
        }


        // GET: Orders/CompletePayment/2

Bangazon/Controllers/PaymentTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bangazon.Data;
using Bangazon.Models;
using Microsoft.AspNetCore.Identity;

namespace Bangazon.Controllers
{
    public class PaymentTypesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public PaymentTypesController(ApplicationDbContext ctx, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = ctx;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: PaymentTypes
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var paymentTypes = _context.PaymentType.Include(p => p.User).Where(p => p.UserId == user.Id);

            return View(await paymentTypes.ToListAsync());
        }


        // GET: PaymentTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentType = await _context.PaymentType
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PaymentTypeId == id);
            if (paymentType == null)
            {
                return NotFound();
            }

            return View(paymentType);
        }

        // GET: PaymentTypes/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: PaymentTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentTypeId,DateCreated,Description,AccountNumber,UserId")] PaymentType paymentType)
        {
            ModelState.Remove("DateCreated");
            ModelState.Remove("PaymentTypeId");
            ModelState.Remove("UserId");
            ModelState.Remove("User");

            if (ModelState.IsValid)
            {
                var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                paymentType.UserId = currentUser.Id;
                _context.Add(paymentType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", paymentType.UserId);
            return View(paymentType);
        }

        // GET: PaymentTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentType = await _context.PaymentType.FindAsync(id);
            if (paymentType == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", paymentType.UserId);
            return View(paymentType);
        }

        // POST: PaymentTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentTypeId,DateCreated,Description,AccountNumber,UserId")] PaymentType paymentType)
        {
            if (id != paymentType.PaymentTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paymentType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentTypeExists(paymentType.PaymentTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", paymentType.UserId);
            return View(paymentType);
        }

        // GET: PaymentTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paymentType = await _context.PaymentType
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PaymentTypeId == id);
            if (paymentType == null)
            {
                return NotFound();
            }

            return View(paymentType);
        }

        // POST: PaymentTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paymentType = await _context.PaymentType.FindAsync(id);
            _context.PaymentType.Remove(paymentType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentTypeExists(int id)
        {
            return _context.PaymentType.Any(e => e.PaymentTypeId == id);
        }
    }
}

Bangazon/Views/Orders/CloseOrder.cshtml
@model Bangazon.Models.OrderViewModels.OrderCloseViewModel

@{
    ViewData["Title"] = "CloseOrder";
}

<h1>Complete Order</h1>


<form asp-action="CloseOrder">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.OrderId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.User.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.DateCreated)
        </dd>
        @foreach (var item in Model.Order.OrderProducts)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => item.Product)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => item.Product.Title)
                @Html.DisplayFor(model => item.Product.Price)

            </dd>
           
        }



        <div class="form-group">
            <label asp-for="Order.PaymentTypeId" class="control-label"></label>
            <select asp-for="Order.PaymentTypeId" class="form-control" asp-items="Model.PaymentTypes"></select>
            <span asp-validation-for="Order.PaymentTypeId" class="text-danger"></span>
        </div>
    </dl>

   
        <input type="hidden" asp-for="@Model.Order.OrderId" />
        <input type="submit" value="Confirm Payment" class="btn btn-danger" /> |
        <a asp-action="ViewCart">Back to Shopping Cart</a>
    </form>

Bangazon/Views/Orders/ConfirmationPage.cshtml
@model Bangazon.Models.Order

@{
    ViewData["Title"] = "ConfirmationPage";
}

<h1>Confirmation Page</h1>

<div>
    <h4>Thank you for your purchase.</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCompleted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCompleted)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaymentType.AccountNumber)
        </dd>
        <dd class="col-sm-10">
            @foreach (var item in Model.OrderProducts)
            {
            <dt class="col-sm-2">
            Purchased
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => item.Product.Title)
                @Html.DisplayFor(model => item.Product.Price)

            </dd>

        }
            </dd>

        </dl>
</div>
<div>
    
    <a asp-action="ViewCart">Go to Cart</a>
</div>

Bangazon/Views/Orders/Delete.cshtml
@model Bangazon.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Cancel Order</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderId)
        </dd>
 
        @foreach (var item in Model.OrderProducts)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => item.Product)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => item.Product.Title)
                @Html.DisplayFor(model => item.Product.Price)

            </dd>
        }


    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ViewCart">Back to Shopping Cart</a>
    </form>
</div>

Bangazon/Views/Orders/DeleteOrderProduct.cshtml
@model Bangazon.Models.OrderProduct

@{
    ViewData["Title"] = "DeleteOrderProduct";
}

<h1>Remove Product from Order</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Order.OrderId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.Price)
        </dd>
    </dl>

    <form asp-action="DeleteOrderProduct">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ViewCart">Back to Shopping Cart</a>
    </form>
</div>

Bangazon/Views/Orders/Index.cshtml
@model IEnumerable<Bangazon.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCompleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCompleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentType.AccountNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrderId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrderId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrderId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Bangazon/Views/Orders/ViewCart.cshtml
@model Bangazon.Models.OrderViewModels.OrderDetailViewModel

@{
    ViewData["Title"] = "ViewCart";
}

<h1>Shopping Cart</h1>
@if (Model.Order == null)
{
    <tr>
        <td>
            <span>Your Shopping Cart is Empty</span>
        </td>
    </tr>
}
else
{
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Order.User)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Order.User.Email)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Order.DateCreated)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Order.DateCreated)
    </dd>

   
  

    @foreach (var item in Model.Order.OrderProducts)
    {
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => item.Product.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => item.Product.Title)
            @Html.DisplayFor(model => item.Product.Price)
          
        </dd>
        <div><a asp-controller="Orders" asp-action="DeleteOrderProduct" asp-route-id="@item.OrderProductId">Delete</a></div>
    }

    <hr />
    <div>
        <a asp-action="Delete" asp-route-id="@Model.Order.OrderId">Cancel Order</a>|
        @if (Model.Order.User.PaymentTypes.Count == 0)
        {
            @Html.ActionLink("Create a payment Type before proceeding", "Create", "PaymentTypes", new { id = Model.Order.User.Id})
        }
        else
        {


            @if (Model.Order.OrderProducts.Count != 0)
            {
                <a asp-action="CloseOrder" asp-route-id="@Model.Order.OrderId">Confirm Shopping Cart</a>
            }
        }



        <br />

        <a asp-action="Index">Back to List</a>
    </div>}